os: Windows Server 2012 R2

configuration:
- Debug
- Release

platform:
- Win32
- x64

build:
  verbosity: detailed

after_build:
  - ps: |
      Copy-Item -Path "group-job\$env:CONFIGURATION\$env:PLATFORM\group-job.exe" `
                -Destination "group-job\$env:CONFIGURATION\group-job-$env:PLATFORM.exe"

artifacts:
  - path: group-job\$(configuration)\group-job-$(platform).exe
    name: $(configuration)\group-job-$(platform).exe

deploy:
  description: Automatic release build of group-job
  provider: GitHub
  auth_token:
    secure: OhF/LMryRiZqCO7NHLqSZcZB1I0Jx19K9OMSmItPvPgv0GwsyhMdSgjk1REkwjmR
  artifact: Release\group-job-Win32.exe,Release\group-job-x64.exe
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
