os: Windows Server 2012 R2

configuration:
- Debug
- Release

platform:
- Win32
- x64

build:
  verbosity: detailed

artifacts:
  - path: Release\Win32\group-job.exe
    name: group-job-x86.exe
  - path: Release\x64\group-job.exe
    name: group-job-x64.exe

deploy:
  description: Automatic release build of group-job
  provider: GitHub
  auth_token:
    secure: OhF/LMryRiZqCO7NHLqSZcZB1I0Jx19K9OMSmItPvPgv0GwsyhMdSgjk1REkwjmR
  artifact: group-job-x86.exe,group-job-x64.exe
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
